[package]
name = "stonefish_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
pleco = "0.5.0"
rayon = "1.5.3"
num_cpus = "1.13.1"
